services:
  # Ollama 服务（生产环境独立容器）
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      # 模型数据持久化
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_GPU_MEMORY_FRACTION=0.8
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '8.0'
        reservations:
          memory: 6G
          cpus: '4.0' 
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 敏感词检测服务（生产环境）
  sensitive-detector:
    build: ./backend
    container_name: sensitive-detector
    ports:
      - "8000:8000"
    volumes:
      # 静态文件目录
      - ./frontend:/app/frontend
      # 词库管理目录
      - ./word_libraries:/app/word_libraries
      # 检测配置文件
      - ./detection_config.json:/app/detection_config.json
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen3:8b-q4_K_M
      - CORS_ALLOW_ORIGINS=*
      - HEALTH_CHECK_ENABLED=true
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# 定义 volumes
volumes:
  ollama_data:
    external: true
    name: sensitive-detector_ollama_data
